DEFINES=USE_SPI_DMA
DEFINES+=NDEBUG

EXTRA_INCLUDES=../lib-device/include ../lib-hal/include

EXTRA_SRCDIR=src/patterns src/pixel src/gd32/gpio src/gd32/i2s

include ../firmware-template-gd32/lib/Rules.mk
