$(info "lib-gd32/Makefile.GD32")
$(info $$FAMILY [${FAMILY}])
$(info $$MAKE_FLAGS [${MAKE_FLAGS}])

DEFINES=NDEBUG

EXTRA_SRCDIR=src/f

ifneq ($(MAKE_FLAGS),)
  	EXTRA_SRCDIR+=gd32f10x/CMSIS/GD/GD32F10x/Source
  	
  	EXTRA_C_SOURCE_FILES+=gd32f10x/GD32F10x_standard_peripheral/Source/gd32f10x_adc.c
  	EXTRA_C_SOURCE_FILES+=gd32f10x/GD32F10x_standard_peripheral/Source/gd32f10x_bkp.c
  	EXTRA_C_SOURCE_FILES+=gd32f10x/GD32F10x_standard_peripheral/Source/gd32f10x_dma.c
  	EXTRA_C_SOURCE_FILES+=gd32f10x/GD32F10x_standard_peripheral/Source/gd32f10x_exti.c
  	EXTRA_C_SOURCE_FILES+=gd32f10x/GD32F10x_standard_peripheral/Source/gd32f10x_fmc.c
  	EXTRA_C_SOURCE_FILES+=gd32f10x/GD32F10x_standard_peripheral/Source/gd32f10x_fwdgt.c
  	EXTRA_C_SOURCE_FILES+=gd32f10x/GD32F10x_standard_peripheral/Source/gd32f10x_gpio.c
  	EXTRA_C_SOURCE_FILES+=gd32f10x/GD32F10x_standard_peripheral/Source/gd32f10x_i2c.c
  	EXTRA_C_SOURCE_FILES+=gd32f10x/GD32F10x_standard_peripheral/Source/gd32f10x_pmu.c
  	EXTRA_C_SOURCE_FILES+=gd32f10x/GD32F10x_standard_peripheral/Source/gd32f10x_rcu.c
  	EXTRA_C_SOURCE_FILES+=gd32f10x/GD32F10x_standard_peripheral/Source/gd32f10x_rtc.c
  	EXTRA_C_SOURCE_FILES+=gd32f10x/GD32F10x_standard_peripheral/Source/gd32f10x_spi.c
  	EXTRA_C_SOURCE_FILES+=gd32f10x/GD32F10x_standard_peripheral/Source/gd32f10x_usart.c
  	EXTRA_C_SOURCE_FILES+=gd32f10x/GD32F10x_standard_peripheral/Source/gd32f10x_timer.c
else
	EXTRA_SRCDIR+=src/uart0 
	EXTRA_SRCDIR+=src/softuart0
endif

include Rules.mk
include ../firmware-template-gd32/lib/Rules.mk