DEFINES+=CONFIG_RDM_ENABLE_SELF_TEST
DEFINES+=CONFIG_RDM_ENABLE_MANUFACTURER_PIDS

DEFINES+=CONFIG_DMXNODE_PIXEL_MAX_PORTS=1
DEFINES+=OUTPUT_DMX_PIXEL 

DEFINES+=DISPLAY_UDF

DEFINES+=CONFIG_STORE_USE_ROM
DEFINES+=DISABLE_FS
